<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>TravelMatch</title>';
echo '<link rel="stylesheet" href="tpstyles.css">';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">';
echo '</head>';
echo '<body>';
echo '<button class="HpBtn" type="button" value="Homepage"><i class="fa fa-long-arrow-left"></i> Back To Home</button>';
echo '<img src="bostonimg.jpg" alt="Boston">';
echo '<header><b>Boston, MA</b></header>';
echo '';
echo '<div class="row">';
echo '<div class="column1">';
echo '<h2>Fast Facts</h2>';
echo '<p>';
echo '<ul>';
echo '<li>';
echo 'Boston was originally named after the town of Boston in England when';
echo 'settlers first came to America.';
echo '</li>';
echo '<li>';
echo 'The first public beach established in the United States can be found in';
echo 'Boston. The location was named Revere Beach and was founded in 1896.';
echo '</li>';
echo '<li>';
echo 'The first Dunkin' Donuts can be found approximately 11 miles from Boston';
echo 'in Quincy, MA. The popular donut shop serves the state's official dessert,';
echo 'Boston Cream Pies.';
echo '</li>';
echo '<li>';
echo 'Boston is home to America's deepest underground tunnel. Tourists can drive';
echo 'through this tunnel at about 90 feet below the surface.';
echo '</li>';
echo '<li>';
echo 'There is a tower that predicts the weather. The tower is referred to as the';
echo 'John Hancock Tower and blinks different colors to let visitors and citizens';
echo 'know what the weather will be like that day whether it be snowy, rainy, cloudy,';
echo 'or clear. The tower also blinks red when it rains hard enough that the Red Sox';
echo 'game had to be canceled.';
echo '</li>';
echo '</ul>';
echo '</p>';
echo '</div>';
echo '<div class="column2">';
echo '<h2>Sights to See</h2>';
echo '<p>';
echo '<ul>';
echo '<li>';
echo 'Boston is home to the first college in the United States, and this college is';
echo 'definitely a sight to see. Harvard was founded in 1636, and people are able to';
echo 'visit and receive a tour from a current student to learn about the history of';
echo 'the college while viewing popular landmarks and monuments.';
echo '</li>';
echo '<li>';
echo 'Being the pinnacle of American past times, Fenway Park is an important attraction';
echo 'to any tourist familiar with or fond of the sport of baseball. Getting a ticket to';
echo 'a game in this stadium can be pricey, but visitors are welcome to tour the grounds';
echo 'and take in stories about Babe Ruth and other baseball legends.';
echo '</li>';
echo '<li>';
echo 'The Gardener Museum is home to many pieces of Italian-style art and old fashioned';
echo 'books, but the allure from this museum comes from the mystery that surrounds it.';
echo 'The museum was a victim to two of the most notorious art heists in modern history.';
echo 'Taking place in 1990, one of these heists took an estimated $500 million worth of';
echo 'precious artwork.';
echo '</li>';
echo '<li>';
echo 'Tourists can get the chance to go on a tour of Boston's Freedom Trail.';
echo 'This tour spans approximately 2.5 miles and covers important topics in';
echo 'Boston history such as the Boston Tea Party, the Boston Massacre, and many';
echo 'more.';
echo '</li>';
echo '<li>';
echo 'The Arnold Aboretum offers visitors stunning natural sites. The Aboretum hosts';
echo 'the largest blooming lilac garden in the world. Even when the lilacs are not in';
echo 'bloom, the Aboretum offers a peaceful and quiet place to get away from the city.';
echo '</li>';
echo '</ul>';
echo '</p>';
echo '';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '</body>';
echo '<footer>';
echo '<i class="fa fa-angle-double-right"></i> More detail regarding this information can be found at: <i class="fa fa-angle-double-left"></i> <br>';
echo '<a href="https://www.trolleytours.com/boston/facts">Fast Facts</a><br>';
echo 'and<br> <a href="https://thegetaway.com/destinations/top-rated-tourist-attractions-in-boston-and-cambridge/10/">Sights to See</a></footer>';
echo '</html>';
?>